name: "Run Container Scan on Super Mario Docker Image with Quality Gate"
 
# on:
#   push:
#     branches:
#       - main
 
env:
  VERSION: $(( $(cat version.txt) + 1 ))
  
jobs:
  
  run_container_image_scan_on_supermario_docker_image:
    runs-on: ubuntu-latest	
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
 
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        
      - name: Get Docker Image from Docker Hub
        run: |
          docker pull docker.io/duboisjou0/supermariogitopsproject:${{ env.VERSION }}
          docker save -o supermariolatestdockerimage.tar docker.io/duboisjou0/supermariogitopsproject:${{ env.VERSION }}

      - name: Compute VERSION from version.txt
        run: echo "VERSION=$(( $(cat version.txt) + 1 ))" >> $GITHUB_ENV

      - name: Run Trivy vulnerability scanner (scan image from Docker Hub)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: docker.io/duboisjou0/supermariogitopsproject:${{ env.VERSION }}
          exit-code: '0' #0 to skip vulnerability in docker image'1'
          severity: 'CRITICAL,HIGH'
